/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.4.0
 *
 * Project: 'HWT605_485+HWT605485' 
 * Target:  'HWT605485' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f4xx.h"



#endif /* RTE_COMPONENTS_H */
